### ISSUE TITLE
how to use it with vj4

### ISSUE THREAD

**Issue by HoboChen** [vijos/jd4#32]
as the title

**Comment by iceboy233** [comment]
Point the `server_url` in `config.yaml` to a vj4 server.

It also works if you have multiple vj4 server as a cluster, and point to one of them.

See `examples/config.yaml`.

**Comment by iceboy233** [comment]
plus: the user in vj4 needs to have judge-related privileges. Currently this is `2740` (2048 + 512 + 128 + 32 + 16 + 4). Privileges are defined here: https://github.com/vijos/vj4/blob/master/vj4/model/builtin.py

**Comment by twd2** [comment]
Judges' privileges can be set by `vj4.model.user set_judge [uid]`.
