### ISSUE TITLE
How to modify the languages?

### ISSUE THREAD

**Issue by oovm** [vijos/jd4#41]
If I want to add or reduce some languages, how many files should I modify?
Both in vj4 and jd4. Thx.

**Comment by q234rty** [comment]
For vj4,see vijos/vj4#178 ,note that the [wiki](https://github.com/vijos/vj4/wiki/Add-New-Progrmming-Languages) is outdated.
For jd4,see #29 and #31 .

**Comment by iceboy233** [comment]
Caveats: some compiler/interpreter require special things, such as `js` needs `/dev/urandom` (#29) and `go` needs `/usr/share` (#31). If some new compiler is not working, you can use `strace` _in the sandbox_ to see what's missing.

**Comment by iceboy233** [comment]
#53 adding ruby support

**Comment by oovm** [comment]
Thanks
