### ISSUE TITLE
help~docker run error

### ISSUE THREAD

**Issue by yudiya** [vijos/jd4#65]
![qq 20180606212448](https://user-images.githubusercontent.com/24709058/41040930-5ca2672a-69d0-11e8-8def-69db32c8f7ce.png)

**Comment by twd2** [comment]
More details needed.

**Comment by yanzmgit** [comment]
do you have run the vj4 server already?

**Comment by twd2** [comment]
No more details, closing.

**Comment by zhiwehu** [comment]
I have the same issue. The vj4 server is running on the same machine but the jd4 still said cannot connect...

**Comment by twd2** [comment]
@zhiwehu Your configurations please

**Comment by iceboy233** [comment]
The most common reason for this is that docker creates its own virtual network, so 127.0.0.1 inside docker is not the same address as 127.0.0.1 of the outer machine.
