### ISSUE TITLE
Add more language support for special judge.

### ISSUE THREAD

**Issue by undefined-moe** [vijos/jd4#70]
It seems that the special judge supports .c only.

**Comment by twd2** [comment]
According to https://github.com/vijos/jd4/blob/master/jd4/case.py#L272, https://github.com/vijos/jd4/blob/master/jd4/case.py#L119, and https://github.com/vijos/jd4/blob/master/jd4/case.py#L124, the custom judge (aka. special judge) supports as many languages as a user program. Thus, closing.

Feel free to reopen if you have any updates.

**Comment by undefined-moe** [comment]
![image](https://user-images.githubusercontent.com/29992205/56056679-7835a980-5d8f-11e9-9c64-a4297c0c32ab.png)
I wonder why this happen.

**Comment by twd2** [comment]
Please have a look at https://github.com/vijos/jd4/blob/master/examples/langs.yaml.
so please use `.cc`.

**Comment by undefined-moe** [comment]
I have solved the problem.
Sorry to bother you.
