### ISSUE TITLE
A Bug?

### ISSUE THREAD

**Issue by ghost** [vijos/jd4#9]
![001](https://cloud.githubusercontent.com/assets/26326151/23944363/91ff79b4-09ad-11e7-9b7b-e1ea7d9480ec.png)
It seems like a bug...

**Comment by ghost** [comment]
The link:
https://vijos.org/d/sqc233/records/58c53869d3d8a16c62a244ff

**Comment by q234rty** [comment]
Already Fixed: #3

**Comment by iceboy233** [comment]
rejudged :)
